const nav=document.querySelector("#nav"),menuBtn=document.querySelector("#menuBtn"),modal=document.querySelector("#modal"),closeButton=document.querySelector("#close");
menuBtn.setAttribute("aria-label","Open navigation");menuBtn.setAttribute("aria-expanded","false");
menuBtn.addEventListener("click",()=>{const isOpen=nav.classList.toggle("open");menuBtn.setAttribute("aria-expanded",String(isOpen))});
document.querySelectorAll("nav a").forEach(link=>link.addEventListener("click",()=>{nav.classList.remove("open");menuBtn.setAttribute("aria-expanded","false")}));
document.querySelectorAll(".open").forEach(button=>{button.setAttribute("aria-label","Open project details");button.addEventListener("click",()=>{const project=button.closest("article");document.querySelector("#mcat").textContent="SELECTED WORK";document.querySelector("#mtitle").textContent=project.querySelector("h3").textContent;document.querySelector("#mdesc").textContent=project.querySelector("p").textContent;document.querySelector("#mtools").textContent=project.querySelector("em").textContent;modal.classList.add("show");modal.setAttribute("aria-hidden","false");document.body.style.overflow="hidden";closeButton.focus()})});
function closeModal(){modal.classList.remove("show");modal.setAttribute("aria-hidden","true");document.body.style.overflow=""}closeButton.addEventListener("click",closeModal);modal.addEventListener("click",event=>{if(event.target===modal)closeModal()});document.addEventListener("keydown",event=>{if(event.key==="Escape")closeModal()});
const sections=document.querySelectorAll("main section"),navLinks=document.querySelectorAll("nav a");const sectionObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)navLinks.forEach(link=>link.classList.toggle("active",link.getAttribute("href")===`#${entry.target.id}`))}),{rootMargin:"-30% 0px -60%"});sections.forEach(section=>sectionObserver.observe(section));
const revealItems=document.querySelectorAll(".title,.projects article,.timeline article,.skills>div,.split>div");const revealObserver=new IntersectionObserver((entries,observer)=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("visible");observer.unobserve(entry.target)}}),{threshold:.12});revealItems.forEach(item=>{item.classList.add("reveal");revealObserver.observe(item)});
const scene=document.querySelector(".scene"),canTilt=window.matchMedia("(pointer: fine) and (prefers-reduced-motion: no-preference)").matches;if(canTilt){scene.addEventListener("pointermove",event=>{const bounds=scene.getBoundingClientRect(),x=(event.clientX-bounds.left)/bounds.width-.5,y=(event.clientY-bounds.top)/bounds.height-.5;scene.style.transform=`rotateY(${x*7}deg) rotateX(${-y*7}deg)`});scene.addEventListener("pointerleave",()=>scene.style.transform="rotateY(0) rotateX(0)")}
const contactForm=document.querySelector("#contactForm");contactForm.addEventListener("submit",event=>{event.preventDefault();const data=Object.fromEntries(new FormData(contactForm)),subject=encodeURIComponent(`Portfolio inquiry from ${data.name}`),body=encodeURIComponent(`Name: ${data.name}\nEmail: ${data.email}\n\n${data.message}`);window.location.href=`mailto:vfdelarosa15@gmail.com?subject=${subject}&body=${body}`;document.querySelector("#status").textContent="OPENING YOUR EMAIL APP..."});
